### ISSUE TITLE
No Language indication in repository card

### ISSUE THREAD

**Issue by MohamedDanis** [MohamedDanis/opnhub#23]
Description:
After selecting multiple languages, the repositories are shown below randomly.But I cannot identify the languages of each repo without going inside the github website

Steps to Reproduce:
Go to the search bar.
Enter  language name and select multiple languages.
The repositories are shown in random

Expected Behavior:
Each repository card need a language indication in the card

Actual Behavior:
There is no indication of which language used in the repo

Screen Shot:
![Screenshot 2024-10-03 161753](https://github.com/user-attachments/assets/239ebf4f-7b7e-466f-a153-17ff567e3a64)

Suggested Fix:
Add a language indication in the card

Environment:
Browser: Chrome 117
Operating System: Windows 11

**Comment by imkeanserna** [comment]
@MohamedDanis i would love to work on this, can you please assign it to me?

**Comment by MohamedDanis** [comment]
Thank you for your interest. I want to ensure that everyone gets a fair chance to contribute during Hacktoberfest. If no one is assigned to this issue in the next few days, I will gladly assign it to you. Please stay tuned, and don't worry—your contributions are valued! @imkurosaki

**Comment by imkeanserna** [comment]
@MohamedDanis, that's a great idea! We can switch it to an icon since many repositories use multiple languages. However, the downside is that frequent requests to the GitHub API may hit the rate limit like this:
![image](https://github.com/user-attachments/assets/f083c0aa-7341-471f-9e55-b978be7c484e)
![image](https://github.com/user-attachments/assets/bec8777b-45c4-43f9-9b8f-56103efcbfd5)

**Comment by MohamedDanis** [comment]
the rate limit issue is the next feature/issue need to be implemented,I'm working on it.rn, focus on the design  @imkurosaki

**Comment by LeninKhangjrakpam** [comment]
Hey @MohamedDanis , sorry about the PR without assigning. 
Do you still want to assign this issue to me?

**Comment by MohamedDanis** [comment]
Yeah I can do that, before that we need to discuss about the design

**Comment by LeninKhangjrakpam** [comment]
@MohamedDanis , could you take a look at this? Any feedback or suggestions for improvement would be appreciated.
I’m currently working for a single language per card (due to rate limitation issues for getting multiple language used in a repo).

![image](https://github.com/user-attachments/assets/9ba9bd50-e6cc-427b-a239-ba8c147b38f7)

**Comment by MohamedDanis** [comment]
it's ok,but the color is too vibrant,try the tag background color

**Comment by LeninKhangjrakpam** [comment]
is this better ? 
![image](https://github.com/user-attachments/assets/27541b94-1d89-41ee-8974-6b1f7d53db85)

**Comment by MohamedDanis** [comment]
try using the colors of text inside the tag

**Comment by LeninKhangjrakpam** [comment]
@MohamedDanis 
![image](https://github.com/user-attachments/assets/a98284bc-b7b8-4999-87c1-71af079dc698)

**Comment by MohamedDanis** [comment]
It's ok, make a pr and I will review it @LeninKhangjrakpam

**Comment by MohamedDanis** [comment]
any updates @LeninKhangjrakpam
